export enum SCREEN {
  Login = 'LoginScreen',
  OnBoarding = 'OnBoardingScreen',
  Regestraton = 'RegestrationScreen',
  Forgotpassword = 'ForgotPasswordScreen',
  Verify = 'VerificationScreen',
  Home = 'HomeScreen',
  List = 'ListScreen',
  Notification = 'NotificationScreen',
  Profile = 'ProfileScreen',
  Language = 'LanguageScreen',
  Persnol = 'PersnoldataScreen',
  ExtraCard = 'ExtracardScreen',
  ExtraCardAdd = 'ExtraCardAddScreen',
  MyBooking = 'MyBookinScreen',
}
