export enum SCREEN {
  Login = 'LoginScreen',
  OnBoarding = 'OnBoardingScreen',
  Regestraton = 'RegestrationScreen',
  Forgotpassword = 'ForgotPasswordScreen',
  Verify = 'VerificationScreen',
  Home = 'HomeScreen',
  List = 'ListScreen',
  Notification = 'NotificationScreen',
  Profile = 'ProfileScreen',
  Language = 'LanguageScreen',
  Persnol = 'PersnoldataScreen',
  ExtraCard = 'ExtracardScreen',
  ExtraCardAdd = 'ExtraCardAddScreen',
  MyBooking = 'MyBookinScreen',
  SelectFlight = 'SelectFlightScreen',
  Summary = 'SummaryScreen',
  SummaryMulti = 'SummaryMultiScreen',
  Information = 'InformationScreen',
  InformationContact = 'InformationContactScren',
  CustomerInformation = 'CustomrInformation',
  Informationsteptwo = 'InformationStepTwoScreen',
  BuyLugagge = 'BuyLugaggeScreen',
  EatingScreen = 'EatingScreen',
  BussinesLongue = 'BusinessLongueScreen',
  Tickets = 'TicketsScreen',
}
